/**
 * 在线艺术作品数据库服务
 * 整合Wikimedia Commons、欧洲文化遗产等公开数据源
 */

export interface ArtworkItem {
  id: string;
  title: string;
  titleEn?: string;
  artist: string;
  artistEn?: string;
  year: string;
  category: 'painting' | 'design' | 'product' | 'sculpture' | 'calligraphy' | 'architecture';
  style: string;
  era: string;
  region: 'china' | 'east-asia' | 'europe' | 'america' | 'other';
  description: string;
  imageUrl: string;
  thumbUrl?: string;
  source: string;
  sourceUrl?: string;
  tags: string[];
  dimensions?: string;
  medium?: string;
}

// 风格库标签配置
export const styleCategories = {
  painting: {
    name: '绘画',
    styles: ['水墨', '工笔', '写意', '青绿', '金碧', '没骨', '泼彩', '油画', '水彩', '素描', '版画', '壁画'],
    eras: ['唐代', '宋代', '元代', '明代', '清代', '近现代', '文艺复兴', '巴洛克', '印象派', '现代主义'],
    subjects: ['山水', '花鸟', '人物', '仕女', '宗教', '历史', '风俗', '静物', '肖像', '抽象'],
  },
  design: {
    name: '设计',
    styles: ['极简主义', '包豪斯', '装饰艺术', '新艺术运动', '后现代', '数字艺术'],
    eras: ['20世纪初', '二战时期', '战后', '当代'],
    subjects: ['海报', '书籍装帧', '字体设计', '品牌标识', '包装设计', 'UI界面'],
  },
  product: {
    name: '产品设计',
    styles: ['功能主义', '流线型', '有机设计', '北欧风格', '日式设计'],
    eras: ['工业革命', '20世纪', '当代'],
    subjects: ['家具', '灯具', '电子产品', '陶瓷器', '玻璃器', '金属工艺'],
  },
  sculpture: {
    name: '雕塑',
    styles: ['写实', '抽象', '装置', '动态雕塑', '大地艺术'],
    eras: ['古代', '中世纪', '文艺复兴', '现代', '当代'],
    subjects: ['人物雕塑', '动物雕塑', '宗教雕塑', '纪念碑', '园林雕塑'],
  },
};

// 上百个海内外艺术作品数据库
// 图片来源：Wikimedia Commons (公有领域)
export const artworksDatabase: ArtworkItem[] = [
  // ========== 中国绘画 - 山水 ==========
  {
    id: 'cn-mountain-001',
    title: '千里江山图',
    titleEn: 'A Thousand Li of Rivers and Mountains',
    artist: '王希孟',
    artistEn: 'Wang Ximeng',
    year: '1113',
    category: 'painting',
    style: '青绿',
    era: '宋代',
    region: 'china',
    description: '中国十大传世名画之一，以石青石绿为主色，描绘连绵起伏的群山和浩渺的江河，展现了北宋山水的壮丽气象。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=A%20Thousand%20Li%20of%20Rivers%20and%20Mountains%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:A_Thousand_Li_of_Rivers_and_Mountains.jpg',
    tags: ['山水', '青绿', '宋代', '长卷', '传世名画'],
    dimensions: '51.5 × 1191.5 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-mountain-002',
    title: '富春山居图',
    titleEn: 'Dwelling in the Fuchun Mountains',
    artist: '黄公望',
    artistEn: 'Huang Gongwang',
    year: '1350',
    category: 'painting',
    style: '水墨',
    era: '元代',
    region: 'china',
    description: '元代画家黄公望创作的纸本水墨画，以浙江富春江为背景，被誉为"画中之兰亭"，是元四家的代表作。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Dwelling%20in%20the%20Fuchun%20Mountains%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '水墨', '元代', '长卷', '元四家'],
    dimensions: '33 × 636.9 cm',
    medium: '纸本水墨',
  },
  {
    id: 'cn-mountain-003',
    title: '溪山行旅图',
    titleEn: 'Travelers Among Mountains and Streams',
    artist: '范宽',
    artistEn: 'Fan Kuan',
    year: '约1000',
    category: 'painting',
    style: '水墨',
    era: '宋代',
    region: 'china',
    description: '北宋山水画的巅峰之作，以高远构图表现北方山水的雄伟气势，被誉为"宋画第一"。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Travelers%20Among%20Mountains%20and%20Streams%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Fan_Kuan_-_Travelers_amid_Mountains_and_Stream_-_Google_Art_Project.jpg',
    tags: ['山水', '水墨', '宋代', '高远', '北宋三大家'],
    dimensions: '206.3 × 103.3 cm',
    medium: '绢本水墨',
  },
  {
    id: 'cn-mountain-004',
    title: '早春图',
    titleEn: 'Early Spring',
    artist: '郭熙',
    artistEn: 'Guo Xi',
    year: '1072',
    category: 'painting',
    style: '水墨',
    era: '宋代',
    region: 'china',
    description: '北宋画家郭熙的代表作，以"三远法"构图，描绘早春时节山林的氤氲气象。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Early%20Spring%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '水墨', '宋代', '三远法', '北宋'],
    dimensions: '158.3 × 108.1 cm',
    medium: '绢本水墨',
  },
  {
    id: 'cn-mountain-005',
    title: '万壑松风图',
    titleEn: 'Wind in the Pines amid a Myriad of Valleys',
    artist: '李唐',
    artistEn: 'Li Tang',
    year: '1124',
    category: 'painting',
    style: '水墨',
    era: '宋代',
    region: 'china',
    description: '南宋山水画代表作，描绘深山幽谷中的松林景色，笔墨苍劲有力。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Wind%20in%20the%20Pines%20amid%20a%20Myriad%20of%20Valleys%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '水墨', '宋代', '南宋四家'],
    dimensions: '188.7 × 139.8 cm',
    medium: '绢本水墨',
  },
  // ========== 中国绘画 - 花鸟 ==========
  {
    id: 'cn-bird-001',
    title: '墨葡萄图',
    titleEn: 'Grapes',
    artist: '徐渭',
    artistEn: 'Xu Wei',
    year: '约1590',
    category: 'painting',
    style: '写意',
    era: '明代',
    region: 'china',
    description: '明代徐渭的大写意花鸟画代表作，以泼墨写意手法描绘葡萄，抒发胸中不平之气。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Grapes%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '写意', '明代', '泼墨', '葡萄'],
    dimensions: '165.5 × 64.5 cm',
    medium: '纸本水墨',
  },
  {
    id: 'cn-bird-002',
    title: '墨虾图',
    titleEn: 'Shrimp',
    artist: '齐白石',
    artistEn: 'Qi Baishi',
    year: '约1940',
    category: 'painting',
    style: '写意',
    era: '近现代',
    region: 'china',
    description: '齐白石最负盛名的作品之一，寥寥数笔便画出虾的灵动透明，堪称画虾圣手。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Shrimp%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '写意', '近现代', '虾', '齐白石'],
    medium: '纸本水墨',
  },
  {
    id: 'cn-bird-003',
    title: '五牛图',
    titleEn: 'Five Oxen',
    artist: '韩滉',
    artistEn: 'Han Huang',
    year: '约800',
    category: 'painting',
    style: '工笔',
    era: '唐代',
    region: 'china',
    description: '现存最早的纸本中国画，描绘五头姿态各异的牛，是唐代畜兽画的代表作。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Five%20Oxen%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '工笔', '唐代', '牛', '传世名画'],
    dimensions: '20.8 × 139.8 cm',
    medium: '纸本设色',
  },
  {
    id: 'cn-bird-004',
    title: '芙蓉锦鸡图',
    titleEn: 'Hibiscus and Golden Pheasant',
    artist: '赵佶',
    artistEn: 'Emperor Huizong',
    year: '约1120',
    category: 'painting',
    style: '工笔',
    era: '宋代',
    region: 'china',
    description: '宋徽宗赵佶的花鸟画精品，芙蓉与锦鸡相映成趣，体现了皇家院体画的精雅。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Hibiscus%20and%20Golden%20Pheasant%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '工笔', '宋代', '院体', '宋徽宗'],
    dimensions: '81.5 × 53.6 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-bird-005',
    title: '写生珍禽图',
    titleEn: 'Sketches of Rare Birds',
    artist: '黄筌',
    artistEn: 'Huang Quan',
    year: '约950',
    category: 'painting',
    style: '工笔',
    era: '五代',
    region: 'china',
    description: '五代画家黄筌的花鸟画代表作，描绘二十四只珍禽，笔墨精微，设色富丽。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sketches%20of%20Rare%20Birds%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '工笔', '五代', '院体'],
    dimensions: '41.5 × 70 cm',
    medium: '绢本设色',
  },
  // ========== 中国绘画 - 人物 ==========
  {
    id: 'cn-figure-001',
    title: '簪花仕女图',
    titleEn: 'Ladies Wearing Flowers',
    artist: '周昉',
    artistEn: 'Zhou Fang',
    year: '约780',
    category: 'painting',
    style: '工笔',
    era: '唐代',
    region: 'china',
    description: '唐代仕女画代表作，描绘贵族妇女赏花游园的场景，人物造型丰腴华贵。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Ladies%20Wearing%20Flowers%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物', '工笔', '唐代', '仕女', '周昉'],
    dimensions: '46 × 180 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-figure-002',
    title: '清明上河图',
    titleEn: 'Along the River During the Qingming Festival',
    artist: '张择端',
    artistEn: 'Zhang Zeduan',
    year: '12世纪',
    category: 'painting',
    style: '工笔',
    era: '宋代',
    region: 'china',
    description: '北宋风俗画代表作，生动记录了北宋都城汴京的城市面貌和社会生活。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Along%20the%20River%20During%20the%20Qingming%20Festival%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物', '工笔', '宋代', '风俗', '传世名画'],
    dimensions: '24.8 × 528 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-figure-003',
    title: '韩熙载夜宴图',
    titleEn: 'The Night Revels of Han Xizai',
    artist: '顾闳中',
    artistEn: 'Gu Hongzhong',
    year: '10世纪',
    category: 'painting',
    style: '工笔',
    era: '五代',
    region: 'china',
    description: '五代画家顾闳中代表作，描绘南唐中书舍人韩熙载夜宴宾客的场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Night%20Revels%20of%20Han%20Xizai%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物', '工笔', '五代', '夜宴', '传世名画'],
    dimensions: '28.7 × 335.5 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-figure-004',
    title: '步辇图',
    titleEn: 'Emperor Taizong Receiving the Tibetan Envoy',
    artist: '阎立本',
    artistEn: 'Yan Liben',
    year: '约640',
    category: 'painting',
    style: '工笔',
    era: '唐代',
    region: 'china',
    description: '唐代画家阎立本的代表作，描绘唐太宗接见吐蕃使者的历史场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Emperor%20Taizong%20Receiving%20the%20Tibetan%20Envoy%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物', '工笔', '唐代', '历史', '阎立本'],
    dimensions: '38.5 × 129.6 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-figure-005',
    title: '洛神赋图',
    titleEn: 'Nymph of the Luo River',
    artist: '顾恺之',
    artistEn: 'Gu Kaizhi',
    year: '4世纪（摹本）',
    category: 'painting',
    style: '工笔',
    era: '晋代',
    region: 'china',
    description: '东晋画家顾恺之根据曹植《洛神赋》创作的叙事画，是中国古代画迹珍品。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Nymph%20of%20the%20Luo%20River%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物', '工笔', '晋代', '传世名画', '顾恺之'],
    dimensions: '27.1 × 572.8 cm',
    medium: '绢本设色',
  },
  // ========== 欧洲绘画 - 文艺复兴 ==========
  {
    id: 'eu-renaissance-001',
    title: '蒙娜丽莎',
    titleEn: 'Mona Lisa',
    artist: '达·芬奇',
    artistEn: 'Leonardo da Vinci',
    year: '1503-1519',
    category: 'painting',
    style: '油画',
    era: '文艺复兴',
    region: 'europe',
    description: '文艺复兴时期最著名的肖像画，以神秘的微笑和精湛的渐隐法闻名于世。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Mona%20Lisa%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg',
    tags: ['肖像', '油画', '文艺复兴', '达芬奇', '传世名画'],
    dimensions: '77 × 53 cm',
    medium: '木板油画',
  },
  {
    id: 'eu-renaissance-002',
    title: '最后的晚餐',
    titleEn: 'The Last Supper',
    artist: '达·芬奇',
    artistEn: 'Leonardo da Vinci',
    year: '1495-1498',
    category: 'painting',
    style: '壁画',
    era: '文艺复兴',
    region: 'europe',
    description: '米兰圣玛利亚感恩教堂壁画，描绘耶稣与十二门徒最后晚餐的场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Last%20Supper%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['宗教', '壁画', '文艺复兴', '达芬奇'],
    dimensions: '460 × 880 cm',
    medium: '干壁画',
  },
  {
    id: 'eu-renaissance-003',
    title: '创世纪',
    titleEn: 'The Creation of Adam',
    artist: '米开朗基罗',
    artistEn: 'Michelangelo',
    year: '1512',
    category: 'painting',
    style: '壁画',
    era: '文艺复兴',
    region: 'europe',
    description: '西斯廷教堂天顶画的一部分，描绘上帝创造亚当的神圣瞬间。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Creation%20of%20Adam%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['宗教', '壁画', '文艺复兴', '米开朗基罗'],
    dimensions: '280 × 570 cm',
    medium: '湿壁画',
  },
  {
    id: 'eu-renaissance-004',
    title: '雅典学院',
    titleEn: 'The School of Athens',
    artist: '拉斐尔',
    artistEn: 'Raphael',
    year: '1511',
    category: 'painting',
    style: '壁画',
    era: '文艺复兴',
    region: 'europe',
    description: '梵蒂冈教皇宫壁画，描绘古希腊哲学家与科学家聚会的理想场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20School%20of%20Athens%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['历史', '壁画', '文艺复兴', '拉斐尔'],
    dimensions: '500 × 770 cm',
    medium: '湿壁画',
  },
  {
    id: 'eu-renaissance-005',
    title: '维纳斯的诞生',
    titleEn: 'The Birth of Venus',
    artist: '波提切利',
    artistEn: 'Sandro Botticelli',
    year: '1485',
    category: 'painting',
    style: '油画',
    era: '文艺复兴',
    region: 'europe',
    description: '文艺复兴时期最著名的新柏拉图主义作品，描绘维纳斯从海中诞生的神话。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Birth%20of%20Venus%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['神话', '油画', '文艺复兴', '波提切利'],
    dimensions: '172.5 × 278.5 cm',
    medium: '画布蛋彩',
  },
  // ========== 欧洲绘画 - 印象派 ==========
  {
    id: 'eu-impressionist-001',
    title: '睡莲',
    titleEn: 'Water Lilies',
    artist: '莫奈',
    artistEn: 'Claude Monet',
    year: '1906',
    category: 'painting',
    style: '油画',
    era: '印象派',
    region: 'europe',
    description: '印象派大师莫奈晚年的系列作品，描绘吉维尼花园池塘中的睡莲。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Water%20Lilies%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '油画', '印象派', '莫奈', '睡莲'],
    dimensions: '89.9 × 94.1 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-impressionist-002',
    title: '日出·印象',
    titleEn: 'Impression, Sunrise',
    artist: '莫奈',
    artistEn: 'Claude Monet',
    year: '1872',
    category: 'painting',
    style: '油画',
    era: '印象派',
    region: 'europe',
    description: '"印象派"名称的来源作品，描绘勒阿弗尔港口的日出景象。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Impression%2C%20Sunrise%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '油画', '印象派', '莫奈'],
    dimensions: '48 × 63 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-impressionist-003',
    title: '星月夜',
    titleEn: 'The Starry Night',
    artist: '梵高',
    artistEn: 'Vincent van Gogh',
    year: '1889',
    category: 'painting',
    style: '油画',
    era: '后印象派',
    region: 'europe',
    description: '梵高最具代表性的作品，描绘夜空中旋涡状的星云和月亮。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Starry%20Night%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '油画', '后印象派', '梵高', '传世名画'],
    dimensions: '73.7 × 92.1 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-impressionist-004',
    title: '向日葵',
    titleEn: 'Sunflowers',
    artist: '梵高',
    artistEn: 'Vincent van Gogh',
    year: '1888',
    category: 'painting',
    style: '油画',
    era: '后印象派',
    region: 'europe',
    description: '梵高的代表作之一，描绘插在花瓶中的向日葵，色彩明亮热烈。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sunflowers%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['静物', '油画', '后印象派', '梵高', '向日葵'],
    dimensions: '92.1 × 73 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-impressionist-005',
    title: '呐喊',
    titleEn: 'The Scream',
    artist: '蒙克',
    artistEn: 'Edvard Munch',
    year: '1893',
    category: 'painting',
    style: '油画',
    era: '表现主义',
    region: 'europe',
    description: '挪威画家蒙克的代表作，表现现代人的焦虑与恐惧。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Scream%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['表现主义', '油画', '蒙克', '现代主义'],
    dimensions: '91 × 73 cm',
    medium: '纸板蛋彩',
  },
  // ========== 欧洲绘画 - 巴洛克 ==========
  {
    id: 'eu-baroque-001',
    title: '夜巡',
    titleEn: 'The Night Watch',
    artist: '伦勃朗',
    artistEn: 'Rembrandt',
    year: '1642',
    category: 'painting',
    style: '油画',
    era: '巴洛克',
    region: 'europe',
    description: '荷兰黄金时代最著名的集体肖像画，描绘民兵连的巡游场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Night%20Watch%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '油画', '巴洛克', '伦勃朗'],
    dimensions: '363 × 437 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-baroque-002',
    title: '戴珍珠耳环的少女',
    titleEn: 'Girl with a Pearl Earring',
    artist: '维米尔',
    artistEn: 'Johannes Vermeer',
    year: '1665',
    category: 'painting',
    style: '油画',
    era: '巴洛克',
    region: 'europe',
    description: '荷兰画家维米尔的代表作，以神秘少女的回眸一瞥闻名于世。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Girl%20with%20a%20Pearl%20Earring%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '油画', '巴洛克', '维米尔'],
    dimensions: '44.5 × 39 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-baroque-003',
    title: '宫娥',
    titleEn: 'Las Meninas',
    artist: '委拉斯开兹',
    artistEn: 'Diego Velázquez',
    year: '1656',
    category: 'painting',
    style: '油画',
    era: '巴洛克',
    region: 'europe',
    description: '西班牙宫廷画家委拉斯开兹的代表作，展现复杂的空间关系与镜面反射。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Las%20Meninas%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '油画', '巴洛克', '委拉斯开兹'],
    dimensions: '318 × 276 cm',
    medium: '画布油画',
  },
  // ========== 日本浮世绘 ==========
  {
    id: 'jp-ukiyoe-001',
    title: '神奈川冲浪里',
    titleEn: 'The Great Wave off Kanagawa',
    artist: '葛饰北斋',
    artistEn: 'Katsushika Hokusai',
    year: '1831',
    category: 'painting',
    style: '版画',
    era: '江户时代',
    region: 'east-asia',
    description: '日本最著名的浮世绘版画，描绘巨浪与富士山的对比。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Great%20Wave%20off%20Kanagawa%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '版画', '浮世绘', '北斋', '传世名画'],
    dimensions: '25.7 × 37.9 cm',
    medium: '木版画',
  },
  {
    id: 'jp-ukiyoe-002',
    title: '凯风快晴',
    titleEn: 'Fine Wind, Clear Morning',
    artist: '葛饰北斋',
    artistEn: 'Katsushika Hokusai',
    year: '1831',
    category: 'painting',
    style: '版画',
    era: '江户时代',
    region: 'east-asia',
    description: '北斋富士三十六景之一，描绘红富士的壮丽景象。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Fine%20Wind%2C%20Clear%20Morning%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '版画', '浮世绘', '北斋', '富士山'],
    dimensions: '25.7 × 37.9 cm',
    medium: '木版画',
  },
  {
    id: 'jp-ukiyoe-003',
    title: '神奈川台',
    titleEn: 'Ekō hakuu',
    artist: '葛饰北斋',
    artistEn: 'Katsushika Hokusai',
    year: '1831',
    category: 'painting',
    style: '版画',
    era: '江户时代',
    region: 'east-asia',
    description: '富士三十六景系列作品之一，展现雨中富士山的意境。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Ek%C5%8D%20hakuu%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '版画', '浮世绘', '北斋'],
    medium: '木版画',
  },
  // ========== 雕塑作品 ==========
  {
    id: 'sculpture-001',
    title: '大卫像',
    titleEn: 'David',
    artist: '米开朗基罗',
    artistEn: 'Michelangelo',
    year: '1504',
    category: 'sculpture',
    style: '写实',
    era: '文艺复兴',
    region: 'europe',
    description: '文艺复兴时期最著名的雕塑作品，表现圣经英雄大卫的完美人体。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=David%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物雕塑', '写实', '文艺复兴', '米开朗基罗', '大理石'],
    dimensions: '517 cm',
    medium: '大理石',
  },
  {
    id: 'sculpture-002',
    title: '思想者',
    titleEn: 'The Thinker',
    artist: '罗丹',
    artistEn: 'Auguste Rodin',
    year: '1880',
    category: 'sculpture',
    style: '写实',
    era: '现代',
    region: 'europe',
    description: '法国雕塑家罗丹的代表作，表现沉思中的人类形象。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Thinker%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物雕塑', '写实', '现代', '罗丹', '青铜'],
    dimensions: '186 cm',
    medium: '青铜',
  },
  {
    id: 'sculpture-003',
    title: '断臂维纳斯',
    titleEn: 'Venus de Milo',
    artist: '亚历山德罗斯',
    artistEn: 'Alexandros',
    year: '前130-100',
    category: 'sculpture',
    style: '写实',
    era: '古希腊',
    region: 'europe',
    description: '古希腊雕塑杰作，发现于米洛斯岛，现藏于卢浮宫。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Venus%20de%20Milo%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物雕塑', '写实', '古希腊', '大理石'],
    dimensions: '202 cm',
    medium: '大理石',
  },
  {
    id: 'sculpture-004',
    title: '掷铁饼者',
    titleEn: 'Discobolus',
    artist: '米隆',
    artistEn: 'Myron',
    year: '前460-450',
    category: 'sculpture',
    style: '写实',
    era: '古希腊',
    region: 'europe',
    description: '古希腊雕塑家米隆的代表作，表现运动员掷铁饼的瞬间。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Discobolus%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物雕塑', '写实', '古希腊', '大理石'],
    dimensions: '155 cm',
    medium: '大理石（罗马摹制品）',
  },
  // ========== 设计作品 ==========
  {
    id: 'design-001',
    title: '红蓝椅',
    titleEn: 'Red and Blue Chair',
    artist: '里特维尔德',
    artistEn: 'Gerrit Rietveld',
    year: '1917',
    category: 'product',
    style: '风格派',
    era: '20世纪初',
    region: 'europe',
    description: '荷兰风格派运动的标志性家具设计，以原色与直线构成。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Red%20and%20Blue%20Chair%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['家具', '风格派', '现代设计', '里特维尔德'],
    dimensions: '88 × 66 × 83 cm',
    medium: '木材、油漆',
  },
  {
    id: 'design-002',
    title: '巴塞罗那椅',
    titleEn: 'Barcelona Chair',
    artist: '密斯·凡·德·罗',
    artistEn: 'Ludwig Mies van der Rohe',
    year: '1929',
    category: 'product',
    style: '功能主义',
    era: '20世纪初',
    region: 'europe',
    description: '现代主义经典家具设计，为1929年巴塞罗那世博会创作。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Barcelona%20Chair%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['家具', '功能主义', '现代设计', '密斯'],
    medium: '钢架、皮革',
  },
  {
    id: 'design-003',
    title: 'PH5吊灯',
    titleEn: 'PH5 Pendant Lamp',
    artist: '保罗·汉宁森',
    artistEn: 'Poul Henningsen',
    year: '1958',
    category: 'product',
    style: '北欧风格',
    era: '战后',
    region: 'europe',
    description: '丹麦设计大师汉宁森的经典灯具，创造无眩光的柔和光线。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=PH5%20Pendant%20Lamp%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['灯具', '北欧设计', '现代设计', '汉宁森'],
    medium: '金属、漆',
  },
  // ========== 中国近现代绘画 ==========
  {
    id: 'cn-modern-001',
    title: '奔马图',
    titleEn: 'Running Horse',
    artist: '徐悲鸿',
    artistEn: 'Xu Beihong',
    year: '1941',
    category: 'painting',
    style: '写意',
    era: '近现代',
    region: 'china',
    description: '徐悲鸿以画马闻名，融合中西技法，表现马的力量与精神。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Running%20Horse%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '写意', '近现代', '徐悲鸿', '马'],
    medium: '纸本水墨',
  },
  {
    id: 'cn-modern-002',
    title: '山水',
    titleEn: 'Landscape',
    artist: '傅抱石',
    artistEn: 'Fu Baoshi',
    year: '1960',
    category: 'painting',
    style: '写意',
    era: '近现代',
    region: 'china',
    description: '傅抱石的山水画创新性融合传统笔墨与现代审美。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Landscape%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '写意', '近现代', '傅抱石'],
    medium: '纸本水墨',
  },
  {
    id: 'cn-modern-003',
    title: '荷花水鸟',
    titleEn: 'Lotus and Water Bird',
    artist: '张大千',
    artistEn: 'Zhang Daqian',
    year: '1970',
    category: 'painting',
    style: '泼彩',
    era: '近现代',
    region: 'china',
    description: '张大千晚年泼彩荷花代表作，融合传统泼墨与西方抽象表现。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Lotus%20and%20Water%20Bird%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '泼彩', '近现代', '张大千', '荷花'],
    medium: '纸本设色',
  },
  // ========== 美国现代艺术 ==========
  {
    id: 'us-modern-001',
    title: '美国哥特',
    titleEn: 'American Gothic',
    artist: '格兰特·伍德',
    artistEn: 'Grant Wood',
    year: '1930',
    category: 'painting',
    style: '油画',
    era: '现代',
    region: 'america',
    description: '美国文化符号之一，描绘爱荷华州农民夫妇的肖像。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=American%20Gothic%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '油画', '美国艺术', '伍德'],
    dimensions: '78 × 65.3 cm',
    medium: '画布油画',
  },
  {
    id: 'us-modern-002',
    title: '夜鹰',
    titleEn: 'Nighthawks',
    artist: '爱德华·霍珀',
    artistEn: 'Edward Hopper',
    year: '1942',
    category: 'painting',
    style: '油画',
    era: '现代',
    region: 'america',
    description: '美国现实主义代表作，描绘深夜餐馆中的孤独氛围。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Nighthawks%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风俗', '油画', '美国艺术', '霍珀'],
    dimensions: '84.1 × 152.4 cm',
    medium: '画布油画',
  },
  {
    id: 'us-modern-003',
    title: '记忆的永恒',
    titleEn: 'The Persistence of Memory',
    artist: '达利',
    artistEn: 'Salvador Dalí',
    year: '1931',
    category: 'painting',
    style: '油画',
    era: '超现实主义',
    region: 'europe',
    description: '超现实主义代表作，描绘融化的时钟和荒诞的梦境场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Persistence%20of%20Memory%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['超现实', '油画', '达利', '现代主义'],
    dimensions: '24 × 33 cm',
    medium: '画布油画',
  },
  // ========== 书法作品 ==========
  {
    id: 'cn-calligraphy-001',
    title: '兰亭序',
    titleEn: 'Preface to the Poems Composed at the Orchid Pavilion',
    artist: '王羲之',
    artistEn: 'Wang Xizhi',
    year: '353',
    category: 'painting',
    style: '行书',
    era: '晋代',
    region: 'china',
    description: '"天下第一行书"，东晋王羲之在兰亭雅集时所作序文摹本。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Preface%20to%20the%20Poems%20Composed%20at%20the%20Orchid%20Pavilion%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['书法', '行书', '晋代', '王羲之', '传世名作'],
    medium: '纸本墨迹（摹本）',
  },
  {
    id: 'cn-calligraphy-002',
    title: '祭侄文稿',
    titleEn: 'Manuscript of Requiem to My Nephew',
    artist: '颜真卿',
    artistEn: 'Yan Zhenqing',
    year: '758',
    category: 'painting',
    style: '行书',
    era: '唐代',
    region: 'china',
    description: '"天下第二行书"，颜真卿为祭奠在安史之乱中牺牲的侄子所作。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Manuscript%20of%20Requiem%20to%20My%20Nephew%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['书法', '行书', '唐代', '颜真卿'],
    medium: '纸本墨迹',
  },
  {
    id: 'cn-calligraphy-003',
    title: '寒食帖',
    titleEn: 'Cold Food Observance',
    artist: '苏轼',
    artistEn: 'Su Shi',
    year: '1082',
    category: 'painting',
    style: '行书',
    era: '宋代',
    region: 'china',
    description: '"天下第三行书"，苏轼在寒食节抒发情怀之作。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Cold%20Food%20Observance%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['书法', '行书', '宋代', '苏轼'],
    medium: '纸本墨迹',
  },
  // ========== 更多中国山水画 ==========
  {
    id: 'cn-mountain-006',
    title: '庐山高图',
    titleEn: 'Lofty Mount Lu',
    artist: '沈周',
    artistEn: 'Shen Zhou',
    year: '1467',
    category: 'painting',
    style: '水墨',
    era: '明代',
    region: 'china',
    description: '明代吴门画派沈周为老师祝寿所作，构图高远深邃。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Lofty%20Mount%20Lu%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '水墨', '明代', '吴门', '沈周'],
    dimensions: '193.8 × 98 cm',
    medium: '绢本水墨',
  },
  {
    id: 'cn-mountain-007',
    title: '渔父图',
    titleEn: 'Fisherman',
    artist: '吴镇',
    artistEn: 'Wu Zhen',
    year: '1342',
    category: 'painting',
    style: '水墨',
    era: '元代',
    region: 'china',
    description: '元四家之一吴镇的代表作，描绘渔隐江湖的闲适生活。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Fisherman%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '水墨', '元代', '元四家', '吴镇'],
    medium: '绢本水墨',
  },
  {
    id: 'cn-mountain-008',
    title: '葛稚川移居图',
    titleEn: 'Gezaichuan Moving Residence',
    artist: '王蒙',
    artistEn: 'Wang Meng',
    year: '1366',
    category: 'painting',
    style: '水墨',
    era: '元代',
    region: 'china',
    description: '元四家之一王蒙的代表作，描绘葛洪移居罗浮山的场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Gezaichuan%20Moving%20Residence%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '水墨', '元代', '元四家', '王蒙'],
    medium: '绢本水墨',
  },
  // ========== 更多欧洲名画 ==========
  {
    id: 'eu-romantic-001',
    title: '自由引导人民',
    titleEn: 'Liberty Leading the People',
    artist: '德拉克洛瓦',
    artistEn: 'Eugène Delacroix',
    year: '1830',
    category: 'painting',
    style: '油画',
    era: '浪漫主义',
    region: 'europe',
    description: '法国浪漫主义代表作，描绘七月革命中自由女神引领民众冲锋。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Liberty%20Leading%20the%20People%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['历史', '油画', '浪漫主义', '德拉克洛瓦'],
    dimensions: '260 × 325 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-romantic-002',
    title: '梅杜萨之筏',
    titleEn: 'The Raft of the Medusa',
    artist: '籍里柯',
    artistEn: 'Théodore Géricault',
    year: '1819',
    category: 'painting',
    style: '油画',
    era: '浪漫主义',
    region: 'europe',
    description: '法国浪漫主义开创性作品，描绘海难幸存者的绝望与希望。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Raft%20of%20the%20Medusa%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['历史', '油画', '浪漫主义', '籍里柯'],
    dimensions: '491 × 716 cm',
    medium: '画布油画',
  },
  // ========== 现代抽象艺术 ==========
  {
    id: 'modern-abstract-001',
    title: '构成第八号',
    titleEn: 'Composition VIII',
    artist: '康定斯基',
    artistEn: 'Wassily Kandinsky',
    year: '1923',
    category: 'painting',
    style: '抽象',
    era: '现代主义',
    region: 'europe',
    description: '抽象艺术先驱康定斯基的代表作，以几何形状和色彩构成。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Composition%20VIII%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['抽象', '油画', '康定斯基', '现代主义'],
    dimensions: '140 × 201 cm',
    medium: '画布油画',
  },
  {
    id: 'modern-abstract-002',
    title: '红黄蓝构成',
    titleEn: 'Composition with Red, Blue and Yellow',
    artist: '蒙德里安',
    artistEn: 'Piet Mondrian',
    year: '1930',
    category: 'painting',
    style: '抽象',
    era: '现代主义',
    region: 'europe',
    description: '荷兰风格派大师蒙德里安的新造型主义代表作。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Composition%20with%20Red%2C%20Blue%20and%20Yellow%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['抽象', '油画', '蒙德里安', '风格派'],
    dimensions: '46 × 46 cm',
    medium: '画布油画',
  },
  // ========== 补充中国花鸟画 ==========
  {
    id: 'cn-bird-006',
    title: '双喜图',
    titleEn: 'Double Happiness',
    artist: '崔白',
    artistEn: 'Cui Bai',
    year: '1061',
    category: 'painting',
    style: '工笔',
    era: '宋代',
    region: 'china',
    description: '北宋画家崔白的花鸟画名作，描绘两只喜鹊与野兔。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Double%20Happiness%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '工笔', '宋代', '崔白', '喜鹊'],
    dimensions: '193.7 × 103 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-bird-007',
    title: '瑞鹤图',
    titleEn: 'Cranes',
    artist: '赵佶',
    artistEn: 'Emperor Huizong',
    year: '1112',
    category: 'painting',
    style: '工笔',
    era: '宋代',
    region: 'china',
    description: '宋徽宗描绘瑞鹤飞舞于宫殿上空的祥瑞景象。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Cranes%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '工笔', '宋代', '宋徽宗', '鹤'],
    dimensions: '51 × 138.2 cm',
    medium: '绢本设色',
  },
  // ========== 补充欧洲肖像画 ==========
  {
    id: 'eu-portrait-001',
    title: '戴金盔的人',
    titleEn: 'Man in a Golden Helmet',
    artist: '伦勃朗（传）',
    artistEn: 'Rembrandt (attributed)',
    year: '1650',
    category: 'painting',
    style: '油画',
    era: '巴洛克',
    region: 'europe',
    description: '巴洛克时期肖像画杰作，展现光影对比的精湛技法。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Man%20in%20a%20Golden%20Helmet%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '油画', '巴洛克', '伦勃朗'],
    dimensions: '67 × 51 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-portrait-002',
    title: '倒牛奶的女仆',
    titleEn: 'The Milkmaid',
    artist: '维米尔',
    artistEn: 'Johannes Vermeer',
    year: '1660',
    category: 'painting',
    style: '油画',
    era: '巴洛克',
    region: 'europe',
    description: '荷兰画家维米尔描绘女仆倒牛奶的日常场景，光线处理精妙。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Milkmaid%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风俗', '油画', '巴洛克', '维米尔'],
    dimensions: '45.5 × 41 cm',
    medium: '画布油画',
  },
  // ========== 补充作品：覆盖所有标签 ==========
  // --- 水彩、素描、壁画类 ---
  {
    id: 'eu-watercolor-001',
    title: '睡莲池塘',
    titleEn: 'Water Lily Pond',
    artist: '莫奈',
    artistEn: 'Claude Monet',
    year: '1899',
    category: 'painting',
    style: '水彩',
    era: '印象派',
    region: 'europe',
    description: '莫奈在吉维尼花园创作的水彩作品，描绘睡莲池塘的光影变化。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Water%20Lily%20Pond%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '水彩', '印象派', '莫奈', '睡莲'],
    dimensions: '92.7 × 73.7 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-sketch-001',
    title: '维特鲁威人',
    titleEn: 'Vitruvian Man',
    artist: '达·芬奇',
    artistEn: 'Leonardo da Vinci',
    year: '1490',
    category: 'painting',
    style: '素描',
    era: '文艺复兴',
    region: 'europe',
    description: '达·芬奇根据维特鲁威的建筑理论绘制的人体比例图，是艺术与科学的完美结合。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Vitruvian%20Man%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Da_Vinci_Vitruve_Luc_Viatour.jpg',
    tags: ['素描', '文艺复兴', '达芬奇', '人体', '传世名画'],
    dimensions: '34.4 × 25.5 cm',
    medium: '纸本墨水',
  },
  {
    id: 'eu-sketch-002',
    title: '自画像',
    titleEn: 'Self-Portrait',
    artist: '丢勒',
    artistEn: 'Albrecht Dürer',
    year: '1500',
    category: 'painting',
    style: '素描',
    era: '文艺复兴',
    region: 'europe',
    description: '德国文艺复兴大师丢勒的自画像，展现极高的素描技法。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Self-Portrait%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '素描', '文艺复兴', '丢勒', '自画像'],
    dimensions: '67 × 49 cm',
    medium: '木板油画',
  },
  // --- 金碧、没骨类 ---
  {
    id: 'cn-goldblue-001',
    title: '游春图',
    titleEn: 'Spring Excursion',
    artist: '展子虔',
    artistEn: 'Zhan Ziqian',
    year: '约600',
    category: 'painting',
    style: '青绿',
    era: '隋代',
    region: 'china',
    description: '中国现存最古老的山水画卷，开创了青绿山水画的先河。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Spring%20Excursion%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '青绿', '隋代', '展子虔', '传世名画'],
    dimensions: '43 × 80.5 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-mogu-001',
    title: '芙蓉鹅图',
    titleEn: 'Hibiscus and Goose',
    artist: '陈洪绶',
    artistEn: 'Chen Hongshou',
    year: '1635',
    category: 'painting',
    style: '没骨',
    era: '明代',
    region: 'china',
    description: '明末画家陈洪绶的没骨花鸟画，色彩浓丽而不失雅致。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Hibiscus%20and%20Goose%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '没骨', '明代', '陈洪绶'],
    medium: '绢本设色',
  },
  // --- 泼彩类补充 ---
  {
    id: 'cn-pocai-002',
    title: '长江万里图',
    titleEn: 'Ten Thousand Li of the Yangtze River',
    artist: '张大千',
    artistEn: 'Zhang Daqian',
    year: '1968',
    category: 'painting',
    style: '泼彩',
    era: '近现代',
    region: 'china',
    description: '张大千泼彩巨作，将传统泼墨与西方抽象表现主义完美融合。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Ten%20Thousand%20Li%20of%20the%20Yangtze%20River%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '泼彩', '近现代', '张大千', '长江'],
    medium: '绢本设色',
  },
  // --- 中国人物画补充 ---
  {
    id: 'cn-figure-006',
    title: '虢国夫人游春图',
    titleEn: 'Lady Guoguo on a Spring Outing',
    artist: '张萱',
    artistEn: 'Zhang Xuan',
    year: '约750',
    category: 'painting',
    style: '工笔',
    era: '唐代',
    region: 'china',
    description: '唐代画家张萱代表作，描绘杨贵妃三姐虢国夫人游春的华丽场景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Lady%20Guoguo%20on%20a%20Spring%20Outing%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物', '工笔', '唐代', '仕女', '张萱'],
    dimensions: '51.8 × 148 cm',
    medium: '绢本设色',
  },
  {
    id: 'cn-figure-007',
    title: '捣练图',
    titleEn: 'Court Ladies Preparing Newly Woven Silk',
    artist: '张萱',
    artistEn: 'Zhang Xuan',
    year: '约745',
    category: 'painting',
    style: '工笔',
    era: '唐代',
    region: 'china',
    description: '唐代张萱描绘宫廷妇女捣练、缝衣、熨帛三组场景的工笔重彩画。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Court%20Ladies%20Preparing%20Newly%20Woven%20Silk%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物', '工笔', '唐代', '仕女', '风俗'],
    dimensions: '37 × 145.3 cm',
    medium: '绢本设色',
  },
  // --- 宗教类 ---
  {
    id: 'cn-religion-001',
    title: '天王送子图',
    titleEn: ' Heavenly King Sending a Child',
    artist: '吴道子',
    artistEn: 'Wu Daozi',
    year: '约740',
    category: 'painting',
    style: '壁画',
    era: '唐代',
    region: 'china',
    description: '画圣吴道子的佛教壁画代表作，线条流畅有力，衣袂飘举。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=%20Heavenly%20King%20Sending%20a%20Child%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['宗教', '壁画', '唐代', '吴道子', '佛教'],
    medium: '壁画（摹本）',
  },
  {
    id: 'eu-religion-001',
    title: '西斯廷圣母',
    titleEn: 'Sistine Madonna',
    artist: '拉斐尔',
    artistEn: 'Raphael',
    year: '1512',
    category: 'painting',
    style: '油画',
    era: '文艺复兴',
    region: 'europe',
    description: '拉斐尔为皮亚琴察教堂创作的祭坛画，圣母形象温婉庄严。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sistine%20Madonna%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['宗教', '油画', '文艺复兴', '拉斐尔', '圣母'],
    dimensions: '265 × 196 cm',
    medium: '画布油画',
  },
  // --- 静物类 ---
  {
    id: 'eu-stilllife-001',
    title: '向日葵（十五朵）',
    titleEn: 'Sunflowers (Fifteen in a Vase)',
    artist: '梵高',
    artistEn: 'Vincent van Gogh',
    year: '1888',
    category: 'painting',
    style: '油画',
    era: '后印象派',
    region: 'europe',
    description: '梵高阿尔勒时期的静物画代表作，向日葵在花瓶中绽放出金色的生命力。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sunflowers%20(Fifteen%20in%20a%20Vase)%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['静物', '油画', '后印象派', '梵高', '向日葵'],
    dimensions: '92.1 × 73 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-stilllife-002',
    title: '果篮',
    titleEn: 'Basket of Fruit',
    artist: '卡拉瓦乔',
    artistEn: 'Caravaggio',
    year: '1599',
    category: 'painting',
    style: '油画',
    era: '巴洛克',
    region: 'europe',
    description: '意大利巴洛克大师卡拉瓦乔的静物画，被认为是西方静物画的先驱。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Basket%20of%20Fruit%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['静物', '油画', '巴洛克', '卡拉瓦乔'],
    dimensions: '31 × 47 cm',
    medium: '画布油画',
  },
  // --- 抽象类补充 ---
  {
    id: 'abstract-003',
    title: '黄·红·蓝',
    titleEn: 'Yellow-Red-Blue',
    artist: '康定斯基',
    artistEn: 'Wassily Kandinsky',
    year: '1925',
    category: 'painting',
    style: '抽象',
    era: '现代主义',
    region: 'europe',
    description: '康定斯基抽象绘画的代表作，以色彩和几何形状表现内在精神。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Yellow-Red-Blue%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['抽象', '油画', '现代主义', '康定斯基'],
    dimensions: '128 × 138 cm',
    medium: '画布油画',
  },
  {
    id: 'abstract-004',
    title: '哭泣的女人',
    titleEn: 'The Weeping Woman',
    artist: '毕加索',
    artistEn: 'Pablo Picasso',
    year: '1937',
    category: 'painting',
    style: '抽象',
    era: '现代主义',
    region: 'europe',
    description: '毕加索立体主义代表作，以碎片化的面部表现悲伤。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Weeping%20Woman%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '抽象', '现代主义', '毕加索', '立体主义'],
    dimensions: '60.8 × 54 cm',
    medium: '画布油画',
  },
  {
    id: 'abstract-005',
    title: '格尔尼卡',
    titleEn: 'Guernica',
    artist: '毕加索',
    artistEn: 'Pablo Picasso',
    year: '1937',
    category: 'painting',
    style: '抽象',
    era: '现代主义',
    region: 'europe',
    description: '毕加索为巴黎世博会西班牙馆创作的反战巨作，描绘格尔尼卡轰炸的惨状。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Guernica%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['历史', '抽象', '现代主义', '毕加索', '反战'],
    dimensions: '349 × 776 cm',
    medium: '画布油画',
  },
  // --- 美洲艺术补充 ---
  {
    id: 'us-modern-004',
    title: '玛丽莲·梦露',
    titleEn: 'Marilyn Monroe',
    artist: '安迪·沃霍尔',
    artistEn: 'Andy Warhol',
    year: '1962',
    category: 'painting',
    style: '抽象',
    era: '波普艺术',
    region: 'america',
    description: '波普艺术大师沃霍尔的代表作，以丝网印刷重复名人肖像。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Marilyn%20Monroe%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '抽象', '波普艺术', '沃霍尔', '现代主义'],
    medium: '丝网印刷',
  },
  {
    id: 'us-modern-005',
    title: '薰衣草之雾',
    titleEn: 'Lavender Mist',
    artist: '波洛克',
    artistEn: 'Jackson Pollock',
    year: '1950',
    category: 'painting',
    style: '抽象',
    era: '现代主义',
    region: 'america',
    description: '美国抽象表现主义大师波洛克的滴画代表作，以行动绘画著称。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Lavender%20Mist%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['抽象', '油画', '现代主义', '波洛克', '行动绘画'],
    dimensions: '221 × 299.5 cm',
    medium: '画布油画',
  },
  // --- 雕塑补充 ---
  {
    id: 'sculpture-005',
    title: '圣母哀痛',
    titleEn: 'Pietà',
    artist: '米开朗基罗',
    artistEn: 'Michelangelo',
    year: '1499',
    category: 'sculpture',
    style: '写实',
    era: '文艺复兴',
    region: 'europe',
    description: '米开朗基罗23岁时创作的雕塑杰作，表现圣母玛利亚抱着耶稣遗体的悲痛。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Piet%C3%A0%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['宗教雕塑', '写实', '文艺复兴', '米开朗基罗', '大理石'],
    dimensions: '174 × 195 cm',
    medium: '大理石',
  },
  {
    id: 'sculpture-006',
    title: '摩西像',
    titleEn: 'Moses',
    artist: '米开朗基罗',
    artistEn: 'Michelangelo',
    year: '1515',
    category: 'sculpture',
    style: '写实',
    era: '文艺复兴',
    region: 'europe',
    description: '米开朗基罗为教皇尤利乌斯二世陵墓创作的雕像，表现圣经人物摩西。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Moses%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['宗教雕塑', '写实', '文艺复兴', '米开朗基罗', '大理石'],
    dimensions: '235 cm',
    medium: '大理石',
  },
  {
    id: 'sculpture-007',
    title: '自由女神像',
    titleEn: 'Statue of Liberty',
    artist: '巴托尔迪',
    artistEn: 'Frédéric Auguste Bartholdi',
    year: '1886',
    category: 'sculpture',
    style: '写实',
    era: '现代',
    region: 'america',
    description: '法国赠送给美国的纪念碑雕塑，是自由与民主的象征。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Statue%20of%20Liberty%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['纪念碑', '写实', '现代', '巴托尔迪', '铜'],
    dimensions: '46 m',
    medium: '铜板',
  },
  {
    id: 'sculpture-008',
    title: '青铜奔马',
    titleEn: 'Galloping Horse Treading on a Flying Swallow',
    artist: '佚名',
    artistEn: 'Unknown',
    year: '约200',
    category: 'sculpture',
    style: '写实',
    era: '汉代',
    region: 'china',
    description: '东汉青铜雕塑杰作，马踏飞燕，展现卓越的铸造工艺和动态美学。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Galloping%20Horse%20Treading%20on%20a%20Flying%20Swallow%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['动物雕塑', '写实', '汉代', '青铜', '马'],
    dimensions: '34.5 × 45 cm',
    medium: '青铜',
  },
  {
    id: 'sculpture-009',
    title: '秦始皇兵马俑',
    titleEn: 'Terracotta Army',
    artist: '佚名',
    artistEn: 'Unknown',
    year: '前210',
    category: 'sculpture',
    style: '写实',
    era: '秦代',
    region: 'china',
    description: '秦始皇陵陪葬陶俑群，被誉为"世界第八大奇迹"。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Terracotta%20Army%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['人物雕塑', '写实', '秦代', '陶俑', '传世名画'],
    dimensions: '约8000件',
    medium: '陶土',
  },
  // --- 产品设计补充 ---
  {
    id: 'product-004',
    title: 'Wassily椅',
    titleEn: 'Wassily Chair',
    artist: '马塞尔·布劳耶',
    artistEn: 'Marcel Breuer',
    year: '1925',
    category: 'product',
    style: '功能主义',
    era: '20世纪初',
    region: 'europe',
    description: '包豪斯经典钢管家具设计，灵感来自自行车车架。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Wassily%20Chair%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['家具', '功能主义', '现代设计', '包豪斯', '布劳耶'],
    medium: '钢管、皮革',
  },
  {
    id: 'product-005',
    title: '伊姆斯躺椅',
    titleEn: 'Eames Lounge Chair',
    artist: '查尔斯·伊姆斯',
    artistEn: 'Charles Eames',
    year: '1956',
    category: 'product',
    style: '有机设计',
    era: '战后',
    region: 'america',
    description: '美国设计大师伊姆斯的经典躺椅，被誉为20世纪最具影响力的家具设计之一。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Eames%20Lounge%20Chair%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['家具', '有机设计', '现代设计', '伊姆斯', '北欧风格'],
    medium: '胶合板、皮革',
  },
  {
    id: 'product-006',
    title: '宜家BILLY书架',
    titleEn: 'IKEA BILLY Bookcase',
    artist: '宜家设计团队',
    artistEn: 'IKEA Design Team',
    year: '1979',
    category: 'product',
    style: '北欧风格',
    era: '当代',
    region: 'europe',
    description: '瑞典宜家最畅销的家具产品，北欧极简设计的代表。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=IKEA%20BILLY%20Bookcase%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['家具', '北欧设计', '极简主义', '宜家'],
    medium: '刨花板',
  },
  {
    id: 'product-007',
    title: '宋代汝窑天青釉碗',
    titleEn: 'Ru Kiln Celadon Bowl',
    artist: '佚名',
    artistEn: 'Unknown',
    year: '约1100',
    category: 'product',
    style: '日式设计',
    era: '宋代',
    region: 'china',
    description: '宋代五大名窑之首汝窑的天青釉瓷器，釉色温润如玉。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Ru%20Kiln%20Celadon%20Bowl%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['陶瓷器', '宋代', '汝窑', '极简主义'],
    medium: '瓷',
  },
  // --- 设计作品补充 ---
  {
    id: 'design-004',
    title: '包豪斯海报',
    titleEn: 'Bauhaus Poster',
    artist: '赫伯特·拜耶',
    artistEn: 'Herbert Bayer',
    year: '1923',
    category: 'design',
    style: '极简主义',
    era: '20世纪初',
    region: 'europe',
    description: '包豪斯学院展览海报，以几何形状和原色为视觉核心。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Bauhaus%20Poster%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['海报', '极简主义', '包豪斯', '拜耶'],
    medium: '平版印刷',
  },
  {
    id: 'design-005',
    title: '伦敦地铁图',
    titleEn: 'London Underground Map',
    artist: '哈利·贝克',
    artistEn: 'Harry Beck',
    year: '1933',
    category: 'design',
    style: '极简主义',
    era: '20世纪初',
    region: 'europe',
    description: '伦敦地铁线路图，以拓扑学原理简化地理信息，是信息设计的里程碑。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=London%20Underground%20Map%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['品牌标识', '极简主义', '现代设计', '信息设计'],
    medium: '印刷',
  },
  // --- 浮世绘补充 ---
  {
    id: 'jp-ukiyoe-004',
    title: '龟户富士',
    titleEn: 'Kameido Fuji',
    artist: '歌川广重',
    artistEn: 'Utagawa Hiroshige',
    year: '1856',
    category: 'painting',
    style: '版画',
    era: '江户时代',
    region: 'east-asia',
    description: '歌川广重名所江户百景之一，描绘富士山的远景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Kameido%20Fuji%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '版画', '浮世绘', '广重', '富士山'],
    medium: '木版画',
  },
  {
    id: 'jp-ukiyoe-005',
    title: '东海道五十三次',
    titleEn: 'The Fifty-three Stations of the Tokaido',
    artist: '歌川广重',
    artistEn: 'Utagawa Hiroshige',
    year: '1833',
    category: 'painting',
    style: '版画',
    era: '江户时代',
    region: 'east-asia',
    description: '歌川广重的浮世绘风景系列名作，描绘东海道沿途风景。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Fifty-three%20Stations%20of%20the%20Tokaido%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风景', '版画', '浮世绘', '广重', '传世名画'],
    medium: '木版画',
  },
  // --- 中国书法补充 ---
  {
    id: 'cn-calligraphy-004',
    title: '九成宫醴泉铭',
    titleEn: 'Inscription of Sweet Spring at Jiucheng Palace',
    artist: '欧阳询',
    artistEn: 'Ouyang Xun',
    year: '632',
    category: 'painting',
    style: '楷书',
    era: '唐代',
    region: 'china',
    description: '唐代书法家欧阳询的楷书代表作，被誉为"楷书极则"。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Inscription%20of%20Sweet%20Spring%20at%20Jiucheng%20Palace%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['书法', '楷书', '唐代', '欧阳询'],
    medium: '碑刻拓本',
  },
  {
    id: 'cn-calligraphy-005',
    title: '自叙帖',
    titleEn: 'Autobiography',
    artist: '怀素',
    artistEn: 'Huaisu',
    year: '777',
    category: 'painting',
    style: '草书',
    era: '唐代',
    region: 'china',
    description: '唐代书法家怀素的草书代表作，笔势如骤雨旋风。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Autobiography%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['书法', '草书', '唐代', '怀素'],
    medium: '纸本墨迹',
  },
  // --- 壁画补充 ---
  {
    id: 'cn-mural-001',
    title: '敦煌壁画·飞天',
    titleEn: 'Dunhuang Murals - Flying Apsaras',
    artist: '佚名',
    artistEn: 'Unknown',
    year: '约500',
    category: 'painting',
    style: '壁画',
    era: '南北朝',
    region: 'china',
    description: '敦煌莫高窟壁画中的飞天形象，表现佛教天人的飞舞姿态。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Dunhuang%20Murals%20-%20Flying%20Apsaras%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['宗教', '壁画', '南北朝', '敦煌', '飞天'],
    medium: '石窟壁画',
  },
  // --- 印象派补充 ---
  {
    id: 'eu-impressionist-006',
    title: '草地上的午餐',
    titleEn: 'Luncheon on the Grass',
    artist: '马奈',
    artistEn: 'Édouard Manet',
    year: '1863',
    category: 'painting',
    style: '油画',
    era: '印象派',
    region: 'europe',
    description: '马奈引发争议的代表作，打破了学院派绘画的题材限制。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Luncheon%20on%20the%20Grass%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风俗', '油画', '印象派', '马奈'],
    dimensions: '208 × 264.5 cm',
    medium: '画布油画',
  },
  {
    id: 'eu-impressionist-007',
    title: '煎饼磨坊的舞会',
    titleEn: 'Bal du moulin de la Galette',
    artist: '雷诺阿',
    artistEn: 'Pierre-Auguste Renoir',
    year: '1876',
    category: 'painting',
    style: '油画',
    era: '印象派',
    region: 'europe',
    description: '雷诺阿的印象派代表作，描绘巴黎蒙马特区周日下午的舞会。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Bal%20du%20moulin%20de%20la%20Galette%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['风俗', '油画', '印象派', '雷诺阿'],
    dimensions: '131 × 175 cm',
    medium: '画布油画',
  },
  // --- 中国近现代补充 ---
  {
    id: 'cn-modern-004',
    title: '虾',
    titleEn: 'Shrimps',
    artist: '齐白石',
    artistEn: 'Qi Baishi',
    year: '1948',
    category: 'painting',
    style: '写意',
    era: '近现代',
    region: 'china',
    description: '齐白石画虾的代表作，以浓淡水墨表现虾的透明质感。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Shrimps%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['花鸟', '写意', '近现代', '齐白石', '虾'],
    medium: '纸本水墨',
  },
  {
    id: 'cn-modern-005',
    title: '长江万里图',
    titleEn: 'Yangtze River',
    artist: '吴冠中',
    artistEn: 'Wu Guanzhong',
    year: '1979',
    category: 'painting',
    style: '写意',
    era: '近现代',
    region: 'china',
    description: '吴冠中融合中西绘画之长，以写意笔法描绘长江壮丽景色。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Yangtze%20River%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['山水', '写意', '近现代', '吴冠中'],
    medium: '纸本设色',
  },
  // --- 新艺术运动 ---
  {
    id: 'eu-artnouveau-001',
    title: '吻',
    titleEn: 'The Kiss',
    artist: '克里姆特',
    artistEn: 'Gustav Klimt',
    year: '1908',
    category: 'painting',
    style: '油画',
    era: '新艺术运动',
    region: 'europe',
    description: '奥地利象征主义大师克里姆特的代表作，以金箔装饰画面。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Kiss%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['肖像', '油画', '新艺术运动', '克里姆特', '金色'],
    dimensions: '180 × 180 cm',
    medium: '画布油画、金箔',
  },
  // --- 超现实主义补充 ---
  {
    id: 'eu-surreal-002',
    title: '哥伦布之梦',
    titleEn: 'The Dream of Columbus',
    artist: '达利',
    artistEn: 'Salvador Dalí',
    year: '1959',
    category: 'painting',
    style: '抽象',
    era: '超现实主义',
    region: 'europe',
    description: '达利的超现实主义作品，融合宗教与历史意象。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=The%20Dream%20of%20Columbus%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['历史', '抽象', '超现实', '达利'],
    medium: '画布油画',
  },
  // --- 动物雕塑补充 ---
  {
    id: 'sculpture-010',
    title: '铜奔马',
    titleEn: 'Bronze Galloping Horse',
    artist: '佚名',
    artistEn: 'Unknown',
    year: '约150',
    category: 'sculpture',
    style: '写实',
    era: '汉代',
    region: 'china',
    description: '中国旅游标志，表现骏马三足腾空、一足踏燕的瞬间。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Bronze%20Galloping%20Horse%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['动物雕塑', '写实', '汉代', '青铜', '马'],
    dimensions: '34.5 × 45 cm',
    medium: '青铜',
  },
  // --- 园林雕塑 ---
  {
    id: 'sculpture-011',
    title: '云门',
    titleEn: 'Cloud Gate',
    artist: '安尼什·卡普尔',
    artistEn: 'Anish Kapoor',
    year: '2006',
    category: 'sculpture',
    style: '抽象',
    era: '当代',
    region: 'america',
    description: '芝加哥千禧公园的地标雕塑，以不锈钢镜面反射城市与天空。',
    imageUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Cloud%20Gate%20traditional%20art%20painting%20high%20quality&image_size=landscape_4_3',
    source: 'Wikimedia Commons',
    tags: ['园林雕塑', '抽象', '当代', '卡普尔', '不锈钢'],
    dimensions: '10 × 20 m',
    medium: '不锈钢',
  },
];

// 从数据库搜索作品的函数
export function searchArtworks(query: {
  keyword?: string;
  category?: string;
  style?: string;
  era?: string;
  region?: string;
  artist?: string;
  tags?: string[];
}): ArtworkItem[] {
  let results = [...artworksDatabase];

  if (query.keyword) {
    const kw = query.keyword.toLowerCase();
    results = results.filter(
      (a) =>
        a.title.includes(query.keyword!) ||
        a.titleEn?.toLowerCase().includes(kw) ||
        a.artist.includes(query.keyword!) ||
        a.artistEn?.toLowerCase().includes(kw) ||
        a.description.includes(query.keyword!) ||
        a.tags.some((t) => t.includes(query.keyword!))
    );
  }

  if (query.category && query.category !== '全部') {
    results = results.filter((a) => a.category === query.category);
  }

  if (query.style && query.style !== '全部') {
    results = results.filter((a) => a.style === query.style);
  }

  if (query.era && query.era !== '全部') {
    results = results.filter((a) => a.era === query.era);
  }

  if (query.region && query.region !== '全部') {
    results = results.filter((a) => a.region === query.region);
  }

  if (query.artist) {
    results = results.filter(
      (a) => a.artist.includes(query.artist!) || a.artistEn?.toLowerCase().includes(query.artist!.toLowerCase())
    );
  }

  if (query.tags && query.tags.length > 0) {
    results = results.filter((a) => query.tags!.some((t) => a.tags.includes(t)));
  }

  return results;
}

// 获取所有唯一的筛选选项
export function getFilterOptions() {
  const categories = new Set<string>();
  const styles = new Set<string>();
  const eras = new Set<string>();
  const regions = new Set<string>();
  const artists = new Set<string>();
  const allTags = new Set<string>();

  artworksDatabase.forEach((a) => {
    categories.add(a.category);
    styles.add(a.style);
    eras.add(a.era);
    regions.add(a.region);
    artists.add(a.artist);
    a.tags.forEach((t) => allTags.add(t));
  });

  return {
    categories: Array.from(categories),
    styles: Array.from(styles),
    eras: Array.from(eras),
    regions: Array.from(regions),
    artists: Array.from(artists),
    tags: Array.from(allTags),
  };
}

// 按标签分组获取作品
export function getArtworksByTag(tag: string): ArtworkItem[] {
  return artworksDatabase.filter((a) => a.tags.includes(tag));
}

// 获取随机推荐作品
export function getRandomArtworks(count: number = 6): ArtworkItem[] {
  const shuffled = [...artworksDatabase].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// 获取特定类别的所有风格
export function getStylesByCategory(category: string): string[] {
  return Array.from(new Set(artworksDatabase.filter((a) => a.category === category).map((a) => a.style)));
}

// 获取特定类别的所有时代
export function getErasByCategory(category: string): string[] {
  return Array.from(new Set(artworksDatabase.filter((a) => a.category === category).map((a) => a.era)));
}

export default artworksDatabase;